### ISSUE TITLE
Plugin stopped working

### ISSUE THREAD

**Issue by ghost** [bram-is/homebridge-slide-shutter#6]
After a while of using the plugin, it seems to have stopped working. My curtains won’t open nor close while using Homekit.

**Comment by bramsmulders** [comment]
Hi @0ghj04hjyg9045 can you please provide more info as per this template: 



**Describe The Bug:**


**To Reproduce:**


**Expected behavior:**


**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**


**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by bramsmulders** [comment]
Closed due to no response from @0ghj04hjyg9045
